"""Explicit, ordered C08 schema migrations. No user data is logged."""

from course2career.database_backend import DatabaseBackend

SCHEMA_VERSION = 3

AUTH_SESSIONS_DDL = (
    """CREATE TABLE IF NOT EXISTS auth_sessions (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        token_hash TEXT NOT NULL UNIQUE,
        session_version INTEGER NOT NULL,
        created_time TEXT NOT NULL,
        expires_time TEXT NOT NULL,
        revoked_time TEXT
    )""",
    "CREATE INDEX IF NOT EXISTS idx_auth_sessions_user_id ON auth_sessions(user_id)",
)


def _migrate_sqlite_auth_sessions(repository, connection) -> None:
    for sql in AUTH_SESSIONS_DDL:
        connection.execute(sql)


def migrate_sqlite(repository, *, target: int = SCHEMA_VERSION) -> None:
    from course2career.product_repository import SQLiteProductRepository
    from course2career.user_repository import SQLiteUserRepository

    with repository._connect() as connection:
        connection.execute("BEGIN IMMEDIATE")
        connection.execute(
            "CREATE TABLE IF NOT EXISTS schema_migrations ("
            "version INTEGER PRIMARY KEY, "
            "applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"
        )
        row = connection.execute(
            "SELECT COALESCE(MAX(version), 0) FROM schema_migrations"
        ).fetchone()
        current = int(row[0])
        if current > SCHEMA_VERSION:
            raise RuntimeError("数据库 schema 高于当前应用支持版本。")
        steps = {
            1: SQLiteUserRepository._initialize_schema,
            2: SQLiteProductRepository._initialize_schema,
            3: _migrate_sqlite_auth_sessions,
        }
        for version in range(current + 1, target + 1):
            steps[version](repository, connection)
            connection.execute(
                "INSERT INTO schema_migrations(version) VALUES (?)", (version,)
            )


def execute_sqlite_statements(connection, script: str) -> None:
    for statement in script.split(";"):
        if statement.strip():
            connection.execute(statement)


POSTGRES_DDL = (
    """CREATE TABLE IF NOT EXISTS users (
        id TEXT PRIMARY KEY, username TEXT NOT NULL,
        username_normalized TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL,
        role TEXT NOT NULL CHECK (role IN ('user','developer','admin')),
        plan TEXT NOT NULL DEFAULT 'free'
            CHECK (plan IN ('free','pro','developer','admin')),
        created_time TEXT NOT NULL, session_version INTEGER NOT NULL DEFAULT 1,
        status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','disabled'))
    )""",
    """CREATE TABLE IF NOT EXISTS login_attempts (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        scope_id TEXT NOT NULL, username_normalized TEXT NOT NULL,
        attempted_time TEXT NOT NULL
    )""",
    "CREATE INDEX IF NOT EXISTS idx_login_attempt_scope_user_time "
    "ON login_attempts(scope_id, username_normalized, attempted_time)",
    """CREATE TABLE IF NOT EXISTS api_usage (
        id TEXT PRIMARY KEY, user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
        guest_session_id TEXT, provider TEXT NOT NULL, model TEXT NOT NULL,
        key_mode TEXT NOT NULL CHECK (key_mode IN ('system','user')),
        input_tokens INTEGER NOT NULL DEFAULT 0 CHECK (input_tokens >= 0),
        output_tokens INTEGER NOT NULL DEFAULT 0 CHECK (output_tokens >= 0),
        cost NUMERIC NOT NULL DEFAULT 0 CHECK (cost >= 0),
        cost_status TEXT NOT NULL DEFAULT 'unknown'
            CHECK (cost_status IN ('estimated','unknown')),
        status TEXT NOT NULL, created_time TEXT NOT NULL,
        CHECK (user_id IS NOT NULL OR guest_session_id IS NOT NULL)
    )""",
    "CREATE INDEX IF NOT EXISTS idx_api_usage_user_time "
    "ON api_usage(user_id, created_time)",
    "CREATE INDEX IF NOT EXISTS idx_api_usage_guest_time "
    "ON api_usage(guest_session_id, created_time)",
    """CREATE TABLE IF NOT EXISTS analysis_records (
        id TEXT PRIMARY KEY,
        user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        job_title TEXT, match_score NUMERIC NOT NULL
            CHECK (match_score >= 0 AND match_score <= 100),
        report_snapshot TEXT NOT NULL, created_time TEXT NOT NULL
    )""",
    "CREATE INDEX IF NOT EXISTS idx_analysis_user_time "
    "ON analysis_records(user_id, created_time)",
    """CREATE TABLE IF NOT EXISTS user_api_keys (
        user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        provider TEXT NOT NULL CHECK (provider IN (
            'openai','deepseek','bailian','openrouter','siliconflow',
            'moonshot','zhipu','minimax','gemini','anthropic')),
        encrypted_key BYTEA NOT NULL, nonce BYTEA NOT NULL CHECK (length(nonce) = 12),
        last_four TEXT NOT NULL, updated_time TEXT NOT NULL,
        PRIMARY KEY (user_id, provider)
    )""",
    """CREATE TABLE IF NOT EXISTS user_provider_profiles (
        user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        provider TEXT NOT NULL, endpoint_id TEXT NOT NULL,
        model_id TEXT NOT NULL, created_time TEXT NOT NULL,
        updated_time TEXT NOT NULL, workspace_id TEXT,
        PRIMARY KEY (user_id, provider)
    )""",
    """CREATE TABLE IF NOT EXISTS user_byok_settings (
        user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
        byok_enabled INTEGER NOT NULL DEFAULT 0 CHECK (byok_enabled IN (0, 1)),
        updated_at TEXT NOT NULL
    )""",
)


def migrate_postgres(backend: DatabaseBackend) -> None:
    with backend.connect() as connection:
        connection.execute("SELECT pg_advisory_xact_lock(809138722)")
        connection.execute(
            "CREATE TABLE IF NOT EXISTS schema_migrations ("
            "version INTEGER PRIMARY KEY, "
            "applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"
        )
        row = connection.execute(
            "SELECT COALESCE(MAX(version), 0) FROM schema_migrations"
        ).fetchone()
        current = int(row[0])
        if current > SCHEMA_VERSION:
            raise RuntimeError("数据库 schema 高于当前应用支持版本。")
        if current == 0:
            for sql in POSTGRES_DDL:
                connection.execute(sql)
            connection.execute("INSERT INTO schema_migrations(version) VALUES (1), (2)")
            current = 2
        if current == 2:
            for sql in AUTH_SESSIONS_DDL:
                connection.execute(sql)
            connection.execute("INSERT INTO schema_migrations(version) VALUES (3)")
        elif current < SCHEMA_VERSION:
            raise RuntimeError("不支持未知 PostgreSQL schema 升级路径。")


def schema_version(backend: DatabaseBackend) -> int:
    with backend.connect() as connection:
        return int(
            connection.execute("SELECT MAX(version) FROM schema_migrations").fetchone()[
                0
            ]
        )
